//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdFix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLiterals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLiterals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdFix.StringLiterals", typeof(StringLiterals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept All Updates.
        /// </summary>
        internal static string AcceptAllUpdates {
            get {
                return ResourceManager.GetString("AcceptAllUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to Accept all suggested updates and set their Action to EDIT?  NOTE: The user assumes all risk for inspecting each row marked EDIT for suitability and accuracy.  Format errors will not be marked with EDIT as these require user intervention..
        /// </summary>
        internal static string AcceptAllUpdatesBody {
            get {
                return ResourceManager.GetString("AcceptAllUpdatesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Selection.
        /// </summary>
        internal static string ActionSelection {
            get {
                return ResourceManager.GetString("ActionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Query Fail.
        /// </summary>
        internal static string AdQueryFail {
            get {
                return ResourceManager.GetString("AdQueryFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha2,.
        /// </summary>
        internal static string Alpha2 {
            get {
                return ResourceManager.GetString("Alpha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Pending.
        /// </summary>
        internal static string ApplyPending {
            get {
                return ResourceManager.GetString("ApplyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to Apply the update values for all transactions with an action?  NOTE: The user assumes all risk for inspecting each row marked with Action for suitability and accuracy..
        /// </summary>
        internal static string ApplyPendingBody {
            get {
                return ResourceManager.GetString("ApplyPendingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning query.
        /// </summary>
        internal static string BeginningQuery {
            get {
                return ResourceManager.GetString("BeginningQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blank,.
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Query.
        /// </summary>
        internal static string CancelQuery {
            get {
                return ResourceManager.GetString("CancelQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot page the result set..
        /// </summary>
        internal static string CannotPageResultSet {
            get {
                return ResourceManager.GetString("CannotPageResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character,.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cn.
        /// </summary>
        internal static string Cn {
            get {
                return ResourceManager.GetString("Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co.
        /// </summary>
        internal static string Co {
            get {
                return ResourceManager.GetString("Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom LDAP Filter.
        /// </summary>
        internal static string CustomLdapFilter {
            get {
                return ResourceManager.GetString("CustomLdapFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Dedicated.
        /// </summary>
        internal static string Dedicated {
            get {
                return ResourceManager.GetString("Dedicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryException:  .
        /// </summary>
        internal static string DirectoryException {
            get {
                return ResourceManager.GetString("DirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryNotFoundException:  .
        /// </summary>
        internal static string DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryOperationException:  .
        /// </summary>
        internal static string DirectoryOperationException {
            get {
                return ResourceManager.GetString("DirectoryOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryServicesCOMException:  .
        /// </summary>
        internal static string DirectoryServicesCOMException {
            get {
                return ResourceManager.GetString("DirectoryServicesCOMException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayName.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distinguishedName.
        /// </summary>
        internal static string DistinguishedName {
            get {
                return ResourceManager.GetString("DistinguishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domainpart,.
        /// </summary>
        internal static string DomainPart {
            get {
                return ResourceManager.GetString("DomainPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domains.txt does not exist at {0}.  Reverting to use embedded resources defaultdomains.txt..
        /// </summary>
        internal static string DomainsFileNotFoundMessage {
            get {
                return ResourceManager.GetString("DomainsFileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level domains file not found.
        /// </summary>
        internal static string DomainsFileNotFoundTitle {
            get {
                return ResourceManager.GetString("DomainsFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate,.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time: Query - .
        /// </summary>
        internal static string ElapsedTimeAdQuery {
            get {
                return ResourceManager.GetString("ElapsedTimeAdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time: Duplicate Checks - .
        /// </summary>
        internal static string ElapsedTimeDuplicateChecks {
            get {
                return ResourceManager.GetString("ElapsedTimeDuplicateChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time: Populate DataGridView - .
        /// </summary>
        internal static string ElapsedTimePopulateDataGridView {
            get {
                return ResourceManager.GetString("ElapsedTimePopulateDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: .
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File.
        /// </summary>
        internal static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma Delimited (*.csv)|*.csv|LDAP Data Interchange Format (*.ldf)|*.ldf.
        /// </summary>
        internal static string ExportFileFilter {
            get {
                return ResourceManager.GetString("ExportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Actions.
        /// </summary>
        internal static string FileActions {
            get {
                return ResourceManager.GetString("FileActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format,.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to givenName.
        /// </summary>
        internal static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groupType.
        /// </summary>
        internal static string GroupType {
            get {
                return ResourceManager.GetString("GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeMdb.
        /// </summary>
        internal static string HomeMdb {
            get {
                return ResourceManager.GetString("HomeMdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdFix.
        /// </summary>
        internal static string IdFix {
            get {
                return ResourceManager.GetString("IdFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This privacy statement applies to IdFix only.  It does not apply to any other Microsoft Office 365 server or other applications by Microsoft Corporation. IdFix is intended for IT Administrators.  If you are an end-user, Microsoft recommends that you end this program and contact your IT Administrator for assistance.  IdFix collects data from your corporate network and can optionally store data that may contain personal data in a Comma Separated Value (.csv) or LDAP Data Interchange Format (.ldf) file located [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IdFixPrivacyBody {
            get {
                return ResourceManager.GetString("IdFixPrivacyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdFix Privacy Statement.
        /// </summary>
        internal static string IdFixPrivacyTitle {
            get {
                return ResourceManager.GetString("IdFixPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdFix version {0}.
        /// </summary>
        internal static string IdFixVersionFormat {
            get {
                return ResourceManager.GetString("IdFixVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File.
        /// </summary>
        internal static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma Delimited (*.csv)|*.csv.
        /// </summary>
        internal static string ImportFileFilter {
            get {
                return ResourceManager.GetString("ImportFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isCriticalSystemObject.
        /// </summary>
        internal static string IsCriticalSystemObject {
            get {
                return ResourceManager.GetString("IsCriticalSystemObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEP.
        /// </summary>
        internal static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Connection established.
        /// </summary>
        internal static string LdapConnectionEstablished {
            get {
                return ResourceManager.GetString("LdapConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the LDAP Connection is established..
        /// </summary>
        internal static string LdapConnectionEstablishing {
            get {
                return ResourceManager.GetString("LdapConnectionEstablishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts outside of the server&apos;s domain will not be analyzed for errors.  Do you want to continue?.
        /// </summary>
        internal static string LdapPortWarningMessage {
            get {
                return ResourceManager.GetString("LdapPortWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Global Catalog Port Configured.
        /// </summary>
        internal static string LdapPortWarningTitle {
            get {
                return ResourceManager.GetString("LdapPortWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length,.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit,.
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Updates.
        /// </summary>
        internal static string LoadingUpdates {
            get {
                return ResourceManager.GetString("LoadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localpart,.
        /// </summary>
        internal static string LocalPart {
            get {
                return ResourceManager.GetString("LocalPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailnickname.
        /// </summary>
        internal static string MailNickName {
            get {
                return ResourceManager.GetString("MailNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuAccept.
        /// </summary>
        internal static string MenuAccept {
            get {
                return ResourceManager.GetString("MenuAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Active Directory.
        /// </summary>
        internal static string MenuAD {
            get {
                return ResourceManager.GetString("MenuAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Credentials.
        /// </summary>
        internal static string MenuCurrentCredentials {
            get {
                return ResourceManager.GetString("MenuCurrentCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuDedicated.
        /// </summary>
        internal static string MenuDedicated {
            get {
                return ResourceManager.GetString("MenuDedicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuFeedback.
        /// </summary>
        internal static string MenuFeedback {
            get {
                return ResourceManager.GetString("MenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuFilter.
        /// </summary>
        internal static string MenuFilter {
            get {
                return ResourceManager.GetString("MenuFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other LDAP Directory.
        /// </summary>
        internal static string MenuLDAP {
            get {
                return ResourceManager.GetString("MenuLDAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Active Directories.
        /// </summary>
        internal static string MenuMultipleAD {
            get {
                return ResourceManager.GetString("MenuMultipleAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuMultiTenant.
        /// </summary>
        internal static string MenuMultiTenant {
            get {
                return ResourceManager.GetString("MenuMultiTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuNext.
        /// </summary>
        internal static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Credentials.
        /// </summary>
        internal static string MenuOtherCredentials {
            get {
                return ResourceManager.GetString("MenuOtherCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port 3268.
        /// </summary>
        internal static string MenuPort3268 {
            get {
                return ResourceManager.GetString("MenuPort3268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port 389.
        /// </summary>
        internal static string MenuPort389 {
            get {
                return ResourceManager.GetString("MenuPort389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port 636.
        /// </summary>
        internal static string MenuPort636 {
            get {
                return ResourceManager.GetString("MenuPort636", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuPrevious.
        /// </summary>
        internal static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings - .
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Errors.
        /// </summary>
        internal static string MoreErrors {
            get {
                return ResourceManager.GetString("MoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msExchHideFromAddressLists.
        /// </summary>
        internal static string MsExchHideFromAddressLists {
            get {
                return ResourceManager.GetString("MsExchHideFromAddressLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msExchRecipientTypeDetails.
        /// </summary>
        internal static string MsExchRecipientTypeDetails {
            get {
                return ResourceManager.GetString("MsExchRecipientTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiSelect.
        /// </summary>
        internal static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Multi-Tenant.
        /// </summary>
        internal static string MultiTenant {
            get {
                return ResourceManager.GetString("MultiTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name,.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeric,.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectClass.
        /// </summary>
        internal static string ObjectClass {
            get {
                return ResourceManager.GetString("ObjectClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print DataGridView.
        /// </summary>
        internal static string PrintDataGridView {
            get {
                return ResourceManager.GetString("PrintDataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proposedAction.
        /// </summary>
        internal static string ProposedAction {
            get {
                return ResourceManager.GetString("ProposedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proxyAddresses.
        /// </summary>
        internal static string ProxyAddresses {
            get {
                return ResourceManager.GetString("ProxyAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadDuplicateFile.
        /// </summary>
        internal static string ReadDuplicateFile {
            get {
                return ResourceManager.GetString("ReadDuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadErrorFile.
        /// </summary>
        internal static string ReadErrorFile {
            get {
                return ResourceManager.GetString("ReadErrorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sAMAccountName.
        /// </summary>
        internal static string SamAccountName {
            get {
                return ResourceManager.GetString("SamAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following attributes are present in the schema but are not marked for replication to the Global Catalog and will not be analyzed for errors. Do you want to continue? {0}.
        /// </summary>
        internal static string SchemaWarningMessage {
            get {
                return ResourceManager.GetString("SchemaWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Warning.
        /// </summary>
        internal static string SchemaWarningTitle {
            get {
                return ResourceManager.GetString("SchemaWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory then Query AD.
        /// </summary>
        internal static string SelectDirectorythenQueryAD {
            get {
                return ResourceManager.GetString("SelectDirectorythenQueryAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn.
        /// </summary>
        internal static string Sn {
            get {
                return ResourceManager.GetString("Sn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to targetAddress.
        /// </summary>
        internal static string TargetAddress {
            get {
                return ResourceManager.GetString("TargetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threadsafe Violation.
        /// </summary>
        internal static string Threadsafe {
            get {
                return ResourceManager.GetString("Threadsafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topleveldomain,.
        /// </summary>
        internal static string TopLevelDomain {
            get {
                return ResourceManager.GetString("TopLevelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Updates.
        /// </summary>
        internal static string UndoUpdates {
            get {
                return ResourceManager.GetString("UndoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (*.ldf)|Update*.ldf.
        /// </summary>
        internal static string UpdateFileFilter {
            get {
                return ResourceManager.GetString("UpdateFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userPrincipalName.
        /// </summary>
        internal static string UserPrincipalName {
            get {
                return ResourceManager.GetString("UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Logging.
        /// </summary>
        internal static string VerboseLogging {
            get {
                return ResourceManager.GetString("VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Next Block.
        /// </summary>
        internal static string ViewNextBlock {
            get {
                return ResourceManager.GetString("ViewNextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewPreviousBlock.
        /// </summary>
        internal static string ViewPreviousBlock {
            get {
                return ResourceManager.GetString("ViewPreviousBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Update.
        /// </summary>
        internal static string WriteUpdate {
            get {
                return ResourceManager.GetString("WriteUpdate", resourceCulture);
            }
        }
    }
}
