//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdFix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdFix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_help {
            get {
                object obj = ResourceManager.GetObject("icon_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_filter {
            get {
                object obj = ResourceManager.GetObject("icons_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_filter_hover_16x16 {
            get {
                object obj = ResourceManager.GetObject("icons_filter_hover_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ISO3166 xml:lang=&quot;en&quot;&gt;
        ///&lt;country&gt;&lt;name&gt;Afghanistan&lt;/name&gt;&lt;alpha2&gt;AF&lt;/alpha2&gt;&lt;alpha3&gt;AFG&lt;/alpha3&gt;&lt;numeric&gt;4&lt;/numeric&gt;&lt;/country&gt;
        ///&lt;country&gt;&lt;name&gt;Âland Islands&lt;/name&gt;&lt;alpha2&gt;AX&lt;/alpha2&gt;&lt;alpha3&gt;ALA&lt;/alpha3&gt;&lt;numeric&gt;248&lt;/numeric&gt;&lt;/country&gt;
        ///&lt;country&gt;&lt;name&gt;Albania&lt;/name&gt;&lt;alpha2&gt;AL&lt;/alpha2&gt;&lt;alpha3&gt;ALB&lt;/alpha3&gt;&lt;numeric&gt;8&lt;/numeric&gt;&lt;/country&gt;
        ///&lt;country&gt;&lt;name&gt;Algeria&lt;/name&gt;&lt;alpha2&gt;DZ&lt;/alpha2&gt;&lt;alpha3&gt;DZA&lt;/alpha3&gt;&lt;numeric&gt;12&lt;/numeric&gt;&lt;/country&gt;
        ///&lt;country&gt;&lt;name&gt;American Samoa&lt;/name&gt;&lt;alpha2&gt;AS&lt;/alpha2&gt;&lt;alpha3&gt;ASM&lt;/alpha3&gt;&lt;nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO3166 {
            get {
                return ResourceManager.GetString("ISO3166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap O365_Icon_Feedback {
            get {
                object obj = ResourceManager.GetObject("O365_Icon_Feedback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap O365_Icon_Settings {
            get {
                object obj = ResourceManager.GetObject("O365_Icon_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap office365_logo {
            get {
                object obj = ResourceManager.GetObject("office365_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap office365_logo1 {
            get {
                object obj = ResourceManager.GetObject("office365_logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
